### ISSUE TITLE
Parallelise hyperparameter search on Overtaci

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-t2d#118]
Runs, but gets SSL errors from Wandb. 

What is the next step? Do we even need it?

Currently need to reply to W&B team here: https://public.hey.com/p/YDRCBh4HZBb57eTtFtf3J9e5

Debugging in this branch: https://github.com/Aarhus-Psychiatry-Research/psycop-t2d/tree/wandb_in_parallel

**Comment by HLasse** [comment]
Works fine when I run it, though wandb takes a _long_ time to finish the runs.

**Comment by HLasse** [comment]
Works fine when I run it, though wandb takes a _long_ time to finish the runs.

**Comment by MartinBernstorff** [comment]
@HLasse, when you write "it", can you find what you ran? If it still works fine on your end, I'll re-test on my end :-)

**Comment by HLasse** [comment]
Pretty sure I just ran the multisweep from the readme:

`python src/psycopt2d/train_model.py --multirun +model=xgboost`

(might have added more model types)

**Comment by MartinBernstorff** [comment]
I don't think you ran anything in parallel – the default config doesn't use multithreading ;-) 

![Image](https://user-images.githubusercontent.com/8526086/185588482-7c9fc172-e274-4939-b788-4ac7c11da603.png)

I've created a branch that produces the error: https://github.com/Aarhus-Psychiatry-Research/psycop-t2d/tree/wandb_in_parallel

Can you test that on your end?

**Comment by MartinBernstorff** [comment]
They might be rate-limiting us, but it's a pretty terrible error message: https://docs.wandb.ai/guides/track/limits

**Comment by MartinBernstorff** [comment]
An alternate solution is to do dry_runs, and only upload metrics for the most performant models. 

Also makes the wandb page less cluttered.

**Comment by HLasse** [comment]
I ran it from the `martbern/train_on_overtaci` branch (which is what the PR points to). I assumed it was setup correctly there?

**Comment by HLasse** [comment]
@MartinBernstorff, sure can test it on that branch. Using the same line I pasted earlier? Wonder what their definition of "new account" is.. 
Re dry-runs - for sure also an option - but would be nice to get the full spectrum though

**Comment by MartinBernstorff** [comment]
> I ran it from the `martbern/train_on_overtaci` branch (which is what the PR points to). I assumed it was setup correctly there?

Ran with `python src/psycopt2d/train_model.py --config-name integration_testing --multirun +model=xgboost`

Have added it to the readme as well :-)

**Comment by KennethEnevoldsen** [comment]
(I will just unwatch this - @ me it there is anything)

**Comment by HLasse** [comment]
Works perfectly fine on my end. Suspect it's because my wandb account is older than Martin's (re https://github.com/Aarhus-Psychiatry-Research/psycop-t2d/issues/118#issuecomment-1220454803)
