### ISSUE TITLE
Setup Slack notifications

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-t2d#133]
Do we want this? My thinking is that I frequently miss a test failed on PR and wait an extra minute or two, making context switching more expensive. 

Also, especially as we become a larger group, getting code review requests processed quickly is probably quite important to keep overhead low :-)

@KennethEnevoldsen, @HLasse 
- [ ] Tests failed on PR
- [ ] Code review requests

**Comment by HLasse** [comment]
It is fairly straightforward to set this up to get individual notifications on e.g. failed tests and code review requests, but must be done individually (if in one channel would also be a bunch of spam..). [This guide](https://rasim.pro/blog/personal-slack-github-notifications-for-pull-requests-reviewers-how-to-set-up/) shows how. 
In a nutshell:

Settings -> Scheduled reminders -> Aarhus-psychiatry-research -> Enable real-time alerts and click the ones you want. To get one on failed CI tests, write `pytest` in the box.

Where should we document this? In the wiki?

**Comment by MartinBernstorff** [comment]
This is awesome!

> Where should we document this? In the wiki?

Good question! Probably the wiki, e.g. a "getting set up for dev" page.

**Comment by HLasse** [comment]
On it (the integration is absolutely amazing)

**Comment by HLasse** [comment]
Now documented [here](https://aarhus-wikiatri.chcaa.au.dk/index.php/Set_up_Github_notifications_in_Slack)
