### ISSUE TITLE
Upload only the best performing models to wandb

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-t2d#159]
- [ ] Run with wandb = offline
- [ ] Programmatically select the best runs and upload to wandb

> I ran it from the `martbern/train_on_overtaci` branch (which is what the PR points to). I assumed it was setup correctly there?

Ran with `python src/psycopt2d/train_model.py --config-name integration_testing --multirun +model=xgboost`

Have added it to the readme as well :-)

_Originally posted by @MartinBernstorff in https://github.com/Aarhus-Psychiatry-Research/psycop-t2d/issues/118#issuecomment-1220491208_

**Comment by HLasse** [comment]
Closed by #193
