### ISSUE TITLE
Migrate model_performance to psycop-t2d and fix failing tests on Windows

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-t2d#197]
Evaluation of models should reside in the same repo as model development.

Tests were failing in PR #194 (only on Windows) and on Overtaci, without any obvious reason. 

After migration, reenable the test in `psycopt2d`>`test_calculate_performance_metrics`. If it still fails, debug it.

**Comment by HLasse** [comment]
Closed by #201
