### ISSUE TITLE
Tilføj chromedriver til path på RMAPPS1279

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/psycop-t2d#80]
Vi vil gerne bruge [Altair](https://altair-viz.github.io) til at lave lækre plots i vores projekt. For at kunne gemme det til andet end html/json kræver det man bruger Selenium og dermed har konfigureret [chromedriver](https://chromedriver.chromium.org). 

@mbroend - kan du hente chromedriver og ligge den på et sted der er i alles PATH (også alles conda PATHs)? Det vil gøre vores liv meget nemmere! :)

**Comment by mbroend** [comment]
Tror den er hjemme nu - kunne i hvert fald kalde chromedriver fra random kommandoprompt uden at specificere sti. Men test det lige af og vend tilbage :-)

**Comment by HLasse** [comment]
Det virker perfekt - tusind tak!
