### ISSUE TITLE
Create feature report

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/psycop-t2d#85]
Create an automatic report of
- [ ] Feature generation: resolve_multiple_fns ...
- [ ] Descriptive statistics of the features (skim)
- [ ] Fallback_prop
- [ ] Low variance

**Comment by MartinBernstorff** [comment]
Maybe the code should reside in TSFlattener?

**Comment by HLasse** [comment]
Agreed, will move the issue there
